## Real GA

In this lab we are going to implement: <br>
    * Real population initialization
    * Arithmetic Crossover
    * Guassian Mutation

In [2]:
import numpy as np

In [3]:
def create_initial_pop(pop_size,variables_min,variables_max):
    """
    This function is used to initialize population of random variables within a specific range
    Args:
        pop_size: number of individuals in a population
        variables_min: an array representing the lower limit for each variable in the population ex. [0,5] if we have 2 variables
        variables_max: an array representing the lower limit for each variable in the population ex. [3,9] if we have 2 variables
    """
    # Write your code here
    return init_pop

In [4]:
def arithmetic_crossover (two_parents, pcross):
    """
    This function is used to implement arithmetic crossover.
    We use the following equation:
        offspring = w*parent_one + (1-w)*parent_two
        w is a random number  between 0 and 1
    Args:
        two_parents: a 2d-array (2 X  number of decision variables) 
        pcross: a single value representing the probability of cross over
    """
    # Write your code here:
    return two_children

In [5]:
def gaussian_mutate(individual,sigma,pmute,variables_min, variables_max):
    
    """
    This function is used to implement Gaussian mutation
    Args:
       individual: a 1D array (1 X number of decision variables) representing the chromosome we need to mutate
       sigma: the standard deviation for the Gaussian distribution
       pmute: probability of mutation
       variables_max: an array representing the upper limit for each variable in the population ex. [3,9] if we have 2 variables
       variables_min: an array representing the lower limit for each variable in the population ex. [0,5] if we have 2 variables
   Mutated individual = the original individual + m
   m is a random vector from 1 to chromosome length (= number of decision variables)
   The entries in m are normally distributed according to N(0,sigma)
   The mutated individual is scaled according to the interval of the original parent variables_max,variables_min
    """
    # Write your code here:
    return mutated_individual

In [6]:
def create_initial_pop(pop_size,variables_min,variables_max):
    """
    This function is used to initialize population of random variables within a specific range
    Args:
        pop_size: number of individuals in a population
        variables_min: an array representing the lower limit for each variable in the population ex. [0,5] if we have 2 variables
        variables_max: an array representing the lower limit for each variable in the population ex. [3,9] if we have 2 variables
    """
    number_variables = len(variables_max)
    init_pop = np.zeros((pop_size,number_variables))  
    for i in range(number_variables):
        init_pop[:,i] = np.random.uniform(variables_min[i],variables_max[i],pop_size)
    return init_pop

In [7]:
init_pop = create_initial_pop(15,[0,5],[3,9])
init_pop

array([[ 1.9121908 ,  8.91896722],
       [ 0.11267089,  8.41990187],
       [ 0.58101084,  8.14990573],
       [ 2.74349097,  7.24043913],
       [ 0.59285784,  5.97095971],
       [ 1.28818862,  5.23311514],
       [ 1.00978957,  5.23837845],
       [ 1.35992457,  5.13979773],
       [ 2.48975923,  5.35365057],
       [ 1.21581485,  6.06868271],
       [ 1.12999479,  7.00658683],
       [ 1.25481937,  5.61777247],
       [ 0.77500268,  8.30065051],
       [ 1.10797306,  7.30407068],
       [ 1.81771233,  5.45768216]])

In [8]:
def arithmetic_crossover (two_parents, pcross):
    """
    This function is used to implement arithmetic crossover.
    We use the following equation:
        offspring = w*parent_one + (1-w)*parent_two
        w is a random number  between 0 and 1
    Args:
        two_parents: a 2d-array (2 X  number of decision variables) 
        pcross: a single value representing the probability of cross over
    """
    
    two_children= two_parents[:,:]
    x = np.random.random()
    if  x <= pcross: 
        w1= np.random.random()
        w2= np.random.random()
        two_children[0,:] = w1*two_parents[0,:] + (1-w1)*two_parents[1,:]
        two_children[1,:] = w2*two_parents[0,:] + (1-w2)*two_parents[1,:]
    return two_children

In [9]:
two_parents = init_pop[0:2,:]
two_children = arithmetic_crossover(two_parents, 0.9)
two_children

array([[ 1.0739701 ,  8.68650138],
       [ 0.64167955,  8.56661317]])

In [10]:
def gaussian_mutate(individual,sigma,pmute,variables_min, variables_max):
    
    """
    This function is used to implement Gaussian mutation
    Args:
       individual: a 1D array (1 X number of decision variables) representing the chromosome we need to mutate
       sigma: the standard deviation for the Gaussian distribution
       pmute: probability of mutation
       variables_max: an array representing the upper limit for each variable in the population ex. [3,9] if we have 2 variables
       variables_min: an array representing the lower limit for each variable in the population ex. [0,5] if we have 2 variables
   Mutated individual = the original individual + m
   m is a random vector from 1 to chromosome length (= number of decision variables)
   The entries in m are normally distributed according to N(0,sigma)
   The mutated individual is scaled according to the interval of the original parent variables_max,variables_min
    """
    mutated_individual = individual[:]
    if np.random.random() < pmute:  
        mu = 0
        m = np.random.normal(mu, sigma, len(individual))
        mutated_individual= np.array(individual) + m
        
    for j in range(len(individual)):
        #if the variable breaks the upper and lower limits after mutation, allocate it on the upper or lower boundries
        if mutated_individual[j] > variables_max[j] :
            mutated_individual[j] = variables_max[j]
        elif mutated_individual[j] < variables_min[j] :
            mutated_individual[j] = variables_min[j]

    return mutated_individual

In [11]:
mutated_individual = gaussian_mutate([2.563,8.99],1,1,[0,5], [3,10])
mutated_individual

array([ 2.72541635,  9.02924237])

## Assignment

1. Solve the following optimization problem using Real GA (Note: it is the same problem used in your last assignment):
    Maximize F(x,y) = 8 – (x+ 0.0317)^2 + (y)^2, where -2 ≤ x, y ≤ 2.
    You should follow the same structure we use in the lab notebooks; 
    (there are functions for: population intialization, objective function evaluation, crossover, mutation, 
     selection the main GA ...etc), you will use the following operators: 
        * Tournament Selection
        * Arithmetic crossover
        * Guassian Mutation
2. Submission deadline is 22/3/2019 at 11:59 pm.
3. Please send your assignment to cicourse2014@gmail.com.
4. The email subject should be: YourName_ID_AssignmentNumber.
5. Also the file name should be: YourName_ID_AssignmentNumber.
6. You either send .ipynb file or .py file.
    