We are going to implement oneMax problem. First, we will have a brief introduction about GA pseudo-code then we dive into implementation. 



![caption](Capture.JPG)





In [2]:
import numpy as np

In [7]:
def initPopBinary(npop,clen):  # Use this function to generate the initial population for binary GA
    # npop: population size
    # clen: chromosome length
    # Write your code here:
    pop = np.random.randint(0,2,(npop,clen))
    
    return pop # pop: a 2D  (npop X clen) containing the initial randomly generated population.

In [8]:
pop = initPopBinary(3,7)
pop

array([[1, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0]])

In [9]:
def oneMaxI(chromosome): # Use this function to calculate the fitness function (onemax) for a single chromosome
    # The fitness function used in here is onemax (Number of ones in a chromosome, ex: [1 1 0 0 1], fitness=3)
    # chromosome: single individual from the population
    # Write your code here:
    chromoseomFitness = sum(chromosome)
    return chromoseomFitness # chromoseomFitness: a value representing a specific chromosome fitness value

In [10]:
fitness=oneMaxI([1,1,1,0,0,1])
fitness

4

In [14]:
def oneMaxP(pop,npop): # Use this function to calculate the fitness function for the whole population
    # pop: chromosomes population (2D array (npop X clen))
    # npop: population size
    # Write your code here:
    #popFit = [oneMaxI(i) for i in pop]
    popFit = np.zeros(npop)
    for i in range(npop):
        popFit[i] = oneMaxI(pop[i])
    return popFit # popFit: a one dimension array of the population size (npop) 
    #including the fitness value for all the individuals in the population

In [15]:
#pop = np.array([[1,1,1,0,0,1],[1,1,1,0,0,0]])
popFit = oneMaxP(pop,3)
popFit

array([ 4.,  3.,  2.])

In [16]:
def selectionProb(popFit): # Use this function to calculate the selection probability for each individual in the population
    # popFit: a one dimension array of the population size (npop) including the fitness value 
    # for all the individuals in the population
    # Write your code here:
    #probs =  np.array(popFit, dtype='f')/sum(popFit)
    totalFitness = sum(popFit)
    probs = [i/totalFitness for i in popFit]
    return probs # probs: a one dimension array representing the selection probabilities for every individual in the population

In [17]:
probs = selectionProb(popFit)
probs

[0.44444444444444442, 0.33333333333333331, 0.22222222222222221]

In [18]:
def cumProb(probs): # Use this function to calculate the cummulative probabilities for each individual in the population, 
    # ex: probs= [0.1667, 0.5, 0.0833, 0.25],
    # cprob =[0.1667, 0.6667, 0.75, 1].
    # probs: a one dimension array representing the selection probabilities for every individual in the population
    # Write your code here:
    cprob = np.zeros_like(probs)
    cprob[0] = probs[0]
    for i in range(1,len(probs)):
        cprob[i] = cprob[i-1] + probs[i]
        
    return cprob #cprob a vector representing cummlative probability for each individual in the population

In [19]:
cprob = cumProb(probs)
cprob

array([ 0.44444444,  0.77777778,  1.        ])

In [26]:
def rouletteWheel(cprob): # Use this function to implement the roulette wheel selection, to select a single parent index
    #cprob: cummlative probability for each individual in the population
    # Write your code here:
    r = np.random.random()
    for i in range(len(cprob)):
        if r <= cprob[i]:
            indx = i
            return indx
        
    #return indx # indx: a value represents the index of the selected parent

In [27]:
indx = rouletteWheel(cprob)
indx

2

In [28]:
def rouletteSelect(cprob,pop): # Use this function to return 2 selected parents, 
    #hint: you will use the roulette_wheel function here
    #cprob: a vector representing cummlative probability for each individual in the population
    #pop: chromosomes population (2D array (npop X clen)
    #Write your code here:
    twoParents = np.zeros((2,np.size(pop,1)))
    for i in range(2):
        indx = rouletteWheel(cprob)
        twoParents[i,:] = pop[indx,:]
    return twoParents #twoParents: a (2 X clen) matrix

In [29]:
twoParents = rouletteSelect(cprob,pop)
twoParents

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  1.]])

In [ ]:
def binCross(twoParents, pcross,clen): # Use this function to implement single point cross over
    #twoParents: a (2 X clen) matrix
    # pcross: a single value representing the probability of cross over
    # Write your code here:

    return twoChildren # twoChildren: a (2 X clen) matrix representing the 2 offsprings

In [ ]:
pcross = 1 #I am using 1 just for illustration purposes
clen = len(twoParents[1])
twoChildren = binCross(twoParents, pcross,clen)
twoChildren

In [ ]:
def binMutate(individual,pmute,clen): # Use this function to implement bit flip mutation
    # individual: a 1D array (1 X clen) representing the chromosome we need to mutate
    # pmute: a single value representing the probability of mutation
    # Write your code here:
    
    
    return mutatedInd # mutatedInd: a 1D array (1 X clen) representing the chromosome after mutation

In [ ]:
pmute = 1 #it should be a very small number, I am using 1 just for illustration purposes
individual = twoChildren[1]
clen = len(individual)
mutatedInd = binMutate(individual,pmute,clen)
mutatedInd

In [ ]:
def runBinGA(npop, clen, ngen, pcross, pmute):
    # Use this function as the main function for your code (Put all the functions together)
    # npop: population size
    # clen: chromosome length
    # ngen: number of generations
    # pcross: probability of cross over
    # pmute: probability of mutation

    #Remember the main steps for GA are:
    # 1) Initialization
    # 2) Selection
    # 3) Crossover
    # 4) Mutation
    # 5) Replacement (Here we replace the entire older population with the new one)
    # Write your code here:

    return finpop,bestHist
      # finpop: a 2D array (npop X clen) representing the final population (at the last generation)
      #best_hist: a vector containing the history of highest fitness in the population at each generation

In [ ]:
npop, clen, ngen, pcross, pmute = 30,5,10,2,0.01
finpop,bestHist = runBinGA(npop, clen, ngen, pcross, pmute)

In [ ]:
finpop

In [ ]:
bestHist

## Assignment

1. You need to complete the functions we didn't cover in the lab to finish the GA solving oneMax problem.
2. After solving oneMax, you need to write code to solve the following optimization problem:
    Maximize F(x,y) = 8 – (x+ 0.0317)^2 + (y)^2, where -2 ≤ x, y ≤ 2.
    You should follow the same structure we use in this notebook, mainly you will add functions for: 
        * Binary Decoding
        * Objective function evaluation
        * Ranking Selection
        * Modify the initialization function
3. Submission deadline is 8/3/2019 at 11:59 pm.
4. Please send your assignment to cicourse2014@gmail.com.
5. The email subject should be: YourName_ID_AssignmentNumber.
6. Also the file name should be: YourName_ID_AssignmentNumber.
7. You either send .ipynb file or .py file.
    