In [1]:
#Elitism
#Passing fittest indv into next pop
#two parts one in main, other seperate equation
#sepeare equation part
def getFittest(pop):
    fittest = 0
    popFit = onemax(pop)
    for i in range(len(popFit)):
        if popFit[fittest] <= popFit[i]:
            fittest = i
            
    return fittest

In [2]:
#Help from previous lab
def Fitness(pop):
    return [sum(i) for i in pop]

def onemax(pop):
    #s=sum([sum(i) for i in pop])
    return [sum(i) for i in pop]

In [3]:
import numpy as np
pop=np.random.randint(0,2,size=(5,5))
print(pop)
getFittest(pop)

[[1 1 1 1 0]
 [0 1 1 1 0]
 [1 1 1 0 0]
 [1 0 1 0 0]
 [1 1 0 1 0]]


0

In [4]:
#What if size of elitism is >1
#you need to something in main GA?

### Decoding binary string
$$ \sum_{j=0}^{L-1} x[j]*2^{L-j-1} $$

### and then within specific range
$$ x=x_{min}+\dfrac{\sum_{j=0}^{L-1} x[j]*2^{L-j-1}}{2^L} * (x_{max}-x_{min})$$

In [5]:
#Decoding
#converting from binary values to real one
#using formula you took in lecture
#take indv and ranges
#returns real values
#assume variable length is 5
def decodeInd(binaryInd, R_min=-2,R_max=2,vLength=5):
    l = np.size(binaryInd)
    binsum = 0
    for i in range(l):
        binsum = binsum + binaryInd * (2**(l-i-1))
    
    x = R_min+(binsum/2**(l))*(R_max-R_min)
    return x

In [6]:
import numpy as np
pop=np.random.randint(0,2,size=(5))
print(pop)
#print(np.size(pop))
#print(pop[0])
decodeInd(pop[0],-5,5)

[0 0 0 1 0]


-5.0

In [7]:
#implementation for more than one variable is left for you

### Linear Rank selection
$$ rank Fit = (2- SP)+2(1-SP)* (Rank(i)-1)/(N-1) $$

In [8]:
#Linear Rank
#Problem with roulette wheeel is that when there's large fitness value for indv it'll prevent/
#/other indvs from appearing leads to suboptimal solution
#get sum from 1 to N (N -> number of indv)
#get their rank according to fitness
#apply formula
def LinRank(pop):
    n = np.size(pop,1)
    sp = 1.5
    totalFit = n*(n+1)/2
    res=np.zeros((n))
    popFit = onemax(pop)
    popFit = [sum(pop[i]) for i in range(n)]
    #print(res," ",n)
    #popDict = {ind:FitValue for ind,FitValue in zip(range(n),popFit)}
    popDict = {ind:value for (value, ind) in zip(popFit,range(n))}
    #print(popDict)
    for rank, ind in enumerate(sorted(popDict, key=popDict.get),1):
        #print(rank," ",ind)
        res[ind] = (2-sp)+2*(1-sp)*float(rank-1)/(totalFit-1)
    return res

ls=[2,3,1,5,6]
popDict = {ind:FitValue for ind,FitValue in zip(range(5),ls)}
print(popDict)
print(sorted(popDict, key=popDict.get))

{0: 2, 1: 3, 2: 1, 3: 5, 4: 6}
[2, 0, 1, 3, 4]


In [9]:
pop=np.random.randint(0,2,size=(5,5))
print(pop)
print(np.size(pop,1))
print(LinRank(pop))

[[0 0 0 0 1]
 [0 0 0 1 0]
 [1 0 0 1 1]
 [0 1 0 0 1]
 [1 0 1 1 1]]
5
[0.5        0.42857143 0.28571429 0.35714286 0.21428571]


In [10]:
print(list(range(1,11)))
ls=list(range(1,11))
summation=sum(ls)
n=10
total=n*(n+1)/2
print(summation," ",total)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55   55.0


In [11]:
#
#
#
#
#
#
#
#
#
#
#
#
#

## Practice time
### Tournament selection
### 1)Get population and tournament size (size=2)
### 2)Choose fittest from tournament array
### 3)Then return two parents

In [12]:
def tourSelect(pop, tourSize):
    #We need to get two parents
    #Find a random chosen indivdiual from population
    #repeat previous step with tourSize
    #choose the highest fitness individual from random chosen indviduals
    #the one with highest fitness is considered a parent
    return twoParents
#
#
#
#
#
#
#
#
#
